---
staticips:
  hosts:
  - hostname: gw
    ip: 10.20.0.1
    mac: 00:05:1b:b0:47:9d
  - hostname: storage
    ip: 10.20.0.2
    mac: 0c:c4:7a:a3:25:8a

  - hostname: r1mix # Dell 9020 DESKTOP
    mac: 98:90:96:a7:d8:30
    ip: 10.20.0.10
  - hostname: r1grab # Lenovo T410
    mac: f0:de:f1:49:04:e2
    ip: 10.20.0.11
  - hostname: r1grab2 # Lenovo T410
    mac: f0:de:f1:49:04:ce
    ip: 10.20.0.12
  - hostname: r2mix # Lenovo TP W530
    mac: 3c:97:0e:7f:d8:c0
    ip: 10.20.0.20
  - hostname: r2grab # Lenovo T410
    mac: f0:de:f1:49:04:a8
    ip: 10.20.0.21
  - hostname: r3mix # Lenovo TP W530
    mac: 3c:97:0e:53:ce:07
    ip: 10.20.0.30
  - hostname: r3grab # Lenovo T410
    mac: f0:de:f1:3e:8d:ae
    ip: 10.20.0.31
  - hostname: r4mix # Lenovo TP W530
    mac: 3c:97:0e:9d:af:50
    ip: 10.20.0.40
  - hostname: r4grab # Lenovo T410
    mac: f0:de:f1:49:04:62
    ip: 10.20.0.41
  - hostname: r5mix # Lenovo TP W530
    mac: 3c:97:0e:7f:d9:4c
    ip: 10.20.0.50
  - hostname: r5grab # Lenovo T410
    mac: f0:de:f1:49:72:35
    ip: 10.20.0.51
  - hostname: r6mix # Lenovo TP W530
    mac: 3c:97:0e:23:8c:4c
    ip: 10.20.0.60
  - hostname: r6grab # Lenovo T410
    mac: f0:de:f1:49:04:e5
    ip: 10.20.0.61

  - hostname: r7mix # Lenovo TP W530 ##BROKEN##
    mac: 3c:97:0e:9d:af:4f
    ip: 10.20.0.70
  - hostname: r7grab # Lenovo T61
    mac: 00:1e:37:90:17:77
    ip: 10.20.0.71
  - hostname: r8mix # ASUS 17in
    mac: 14:da:e9:ce:62:b4
    ip: 10.20.0.80
  - hostname: r8grab # Lenovo T410 SPARE
    mac: f0:de:f1:49:72:60
    ip: 10.20.0.81

  - hostname: spare1
    mac: 00:1e:37:90:18:12
  - hostname: spare2
    mac: 00:1e:37:90:18:14
  - hostname: spare3
    mac: 00:1e:37:8e:11:a3
  - hostname: spare4
    mac: 00:1e:37:90:53:d2
  - hostname: spare5
    mac: 00:1e:37:84:1d:09
  - hostname: spare6
    mac: 00:21:86:9a:86:d3
  - hostname: demo2
    mac: c8:5b:76:94:03:dd
  - hostname: edge
    mac: f0:de:f1:77:21:73
  - hostname: minnow1
    disk: /dev/mmcblk2
    mac: 00:08:a2:0b:ba:c8
  - hostname: minnow2
    disk: /dev/mmcblk2
    mac: 00:08:a2:0b:ba:b0
  - hostname: twinpact
    mac: 00:1e:37:90:15:7f
    tasks:
    - ubuntu-desktop
  - hostname: nuc
    mac: f4:4d:30:65:d7:b1

  write_hosts: false
  write_interfaces: false
